MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '../pretrainedModel/swin_base_patch4_window7_224_22k.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'swin_oafr'
  NO_MARGIN: True
  DEVICE_ID: ('1')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [16, 16]
  OCC_AUG: True
  ARC: 'OAFR'
INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10


DATASETS:
  NAMES: ('market1501')
  ROOT_DIR: ('../../dataSet')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 200
  BASE_LR: 2e-03
  IMS_PER_BATCH: 52
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 100
  LOG_PERIOD: 50
  WARMUP_EPOCHS: 5
  EVAL_PERIOD: 20
  WEIGHT_DECAY:  1e-8
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  PERSON_OCC_PRO: 0.5
  PERSON_m: 3
  NEAREST_K: 5
  RECOVER_METHOD: 'soft_label'

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: './logs/occ_duke_swin/swin07210029_100.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './logs/Market_swin_oafr_256/padding'
